### PR TITLE
added d3.fetch

### PR DESCRIPTION
**Pull request by niklas-dahl**
addresses https://github.com/d3/d3-fetch/issues/1

### CODE REVIEW

**Comment by niklas-dahl** [comment]
TODO:
  - [ ] document method in README.md

**Comment by mbostock** [comment]
Hello, and thank you kindly for the contribution!

After further consideration, I think automatic type inference #1 isn’t a good fit for this module, and I apologize if I wasted your time by suggesting it. The first challenge is whether the type should be inferred from the URL (in which case you’d need to, for example, strip off the query string), or from the content-type response header. Unfortunately, neither of those are guaranteed to tell you the type of the response, so trying to implement automatic type inference would add code complexity and also potential confusion (when it doesn’t work). Better, in retrospect, to stick with the explicit named methods that dictate the expected type.

**Comment by niklas-dahl** [comment]
ok, fair enought :)

**Comment by mbostock** [comment]
Thanks for your understanding, and again for contributing!

**Pull request closed without merging**
